# pyproject.toml

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sparseModule"
version = "1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
